apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  labels:
    app: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: beany258/django:1.0.17
          command: ["/bin/sh", "-c"]
          args: ["cd /app && celery -A cwbeany beat -l info"]
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret
          volumeMounts:
            - name: media
              mountPath: /app/media
            - name: static
              mountPath: /app/static
            - name: google-service-account
              mountPath: /app/secrets
              readOnly: true
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: django-media-pvc
        - name: static
          persistentVolumeClaim:
            claimName: django-static-pvc
        - name: google-service-account
          secret:
            secretName: google-service-account 