apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "myapp.local,localhost"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_ENGINE: "django.db.backends.mysql"
  REDIS_HOST: "redis"
  DB_NAME: "blog"
  DB_USER: "blog"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  SERVER_ENV: "K8s"
  ELASTICSEARCH_HOST: "elasticsearch"
  ELASTICSEARCH_PORT: "9200"
