apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "myapp.local,localhost,cwbeany.com"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_ENGINE: "django.db.backends.mysql"
  REDIS_HOST: "redis"
  DB_NAME: "blog"
  DB_USER: "blog"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  SERVER_ENV: "k8s"
  ELASTICSEARCH_HOST: "elasticsearch"
  ELASTICSEARCH_PORT: "9200"
  ELASTICSEARCH_USE_SSL: "false"
  CRON_LOG_DIR: "/app/logs"
  BACKUP_PATH: "/tmp/backup"
  CELERY_BROKER_URL: "redis://redis:6379/1"
  CELERY_RESULT_BACKEND: "redis://redis:6379/1"
  CELERY_ACCEPT_CONTENT: "json"
  CELERY_TASK_SERIALIZER: "json"
  CELERY_RESULT_SERIALIZER: "json"
  CELERY_TIMEZONE: "Asia/Seoul"
