apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - django-rollout.yaml
  - cron-deployment.yaml
  - celery-deployment.yaml
  - celery-beat-deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - pvc.yaml
  - static-pvc.yaml
  # Secret 파일은 Git에 저장하지 않고 직접 적용
  # - secret.yaml
  # - google-service-account-secret.yaml