apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      
      server {
        listen 80;
        client_max_body_size 100M;
        charset utf-8;
        
        location /static/ {
          alias /usr/share/nginx/html/static/;
          autoindex on;
          add_header Cache-Control "public, max-age=31536000";
          add_header Access-Control-Allow-Origin *;
          try_files $uri $uri/ =404;
        }
        
        location /media/ {
          alias /usr/share/nginx/html/media/;
          add_header Cache-Control "public, max-age=31536000";
          add_header Access-Control-Allow-Origin *;
          try_files $uri $uri/ =404;
        }
        
        location / {
          proxy_pass http://prod-django:8000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-CSRFToken $http_x_csrftoken;
        }
      }
    } 