apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: static
              mountPath: /usr/share/nginx/html/static
            - name: media
              mountPath: /usr/share/nginx/html/media
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: static
          persistentVolumeClaim:
            claimName: django-static-pvc
        - name: media
          persistentVolumeClaim:
            claimName: django-media-pvc
