apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - pvc.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboard-json/node-exporter.json
      - dashboard-json/mysql.json
      - dashboard-json/redis.json 