apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cwbeany-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cwadven/cwbeany-app-infra.git
    targetRevision: staging
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: cwbeany-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 