apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cwbeany
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cwadven/cwbeany-app-infra.git
    targetRevision: master
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: cwbeany
  syncPolicy:
    automated:
      prune: true
      selfHeal: true