apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - django
  - mysql
  - redis
  - nginx
  - elasticsearch
  - grafana
  - prometheus
  - mysqld-exporter
  - redis-exporter