apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cwbeany-dev
namePrefix: dev-

resources:
  - ../../base/django
  - ../../base/mysql
  - ../../base/redis
  - ../../base/nginx
  - ../../base/elasticsearch
  - ../../base/grafana
  - ../../base/prometheus
  - ../../base/mysqld-exporter
  - ../../base/redis-exporter

patches:
  - path: resource-patch.yaml
  - path: nginx-config-patch.yaml

configMapGenerator:
  - name: django-config
    behavior: merge
    literals:
      - DJANGO_DEBUG=True
      - ENVIRONMENT=development
      - REDIS_HOST=dev-redis
      - DB_HOST=dev-mysql
      - CELERY_BROKER_URL=redis://dev-redis:6379/1
      - CELERY_RESULT_BACKEND=redis://dev-redis:6379/1
      - ELASTICSEARCH_HOST=dev-elasticsearch
