apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasource
data:
  "datasource.yaml": |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://staging-prometheus:9090
        isDefault: true
        version: 1
        editable: true


