global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'redis'
    static_configs:
      - targets: ['staging-redis-exporter:9121']
  - job_name: 'mysqld'
    static_configs:
      - targets: ['staging-mysqld-exporter:9104'] 