apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
spec:
  template:
    spec:
      containers:
      - name: redis-exporter
        env:
        - name: REDIS_ADDR
          value: redis://staging-redis:6379


